name: Atualizar dataset e criar release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'  # toda segunda às 5h UTC

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy kaggle requests

    - name: Criar kaggle.json a partir do segredo
      run: |
        mkdir -p ~/.kaggle
        echo '${{ secrets.KAGGLE_TOKEN }}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Rodar pipeline Python
      run: python pipeline_dados.py

    - name: Criar e enviar tag automática única
      id: tag
      run: |
        TAG_NAME="release-$(date +'%Y-%m-%d-%H%M%S')"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Criar Release automática
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.tag.outputs.TAG_NAME }}
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        files: dataset_filmes_class.csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
