name: Atualizar dataset e criar release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy kaggle requests

    - name: Criar kaggle.json a partir do segredo
      run: |
        mkdir -p ~/.kaggle

        echo '${{ secrets.KAGGLE_TOKEN }}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        cat ~/.kaggle/kaggle.json

    - name: Debug segredo
      run: 
        echo "Segredo tem conteúdo? [${{ secrets.KAGGLE_TOKEN != '' }}]"

    - name: Verificar se kaggle.json foi criado
      run: |
        ls -lah ~/.kaggle
        cat ~/.kaggle/kaggle.json


    - name: Rodar pipeline Python
      run: python pipeline_dados.py

    - name: Obter data atual
      id: data_atual
      run: echo "data_release=release-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT


    - name: Criar Release com daStaset_filmes_class.csv
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: "Release $(date +'%Y-%m-%d')"  # nome da release pode ter espaços
        tag_name: ${{ steps.data_atual.outputs.data_release }}  # tag sem espaços
        files: dataset_filmes_class.csv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

