name: Atualizar dataset e criar release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1'  # roda toda segunda-feira às 05h

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy kaggle requests

    - name: Criar kaggle.json a partir do segredo
      run: |
        mkdir -p ~/.kaggle
        echo '${{ secrets.KAGGLE_TOKEN }}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Rodar pipeline Python
      run: python pipeline_dados.py

    - name: Criar Release automática
      uses: softprops/action-gh-release@v1
      with:
        name: "Release automática"
        tag_name: "ultima-release"
        files: dataset_filmes_class.csv
        prerelease: false
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
